// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BellIconOutline: typeof import('@heroicons/vue/outline')['BellIcon']
    ChevronDownIconOutline: typeof import('@heroicons/vue/outline')['ChevronDownIcon']
    ChevronLeftIconOutline: typeof import('@heroicons/vue/outline')['ChevronLeftIcon']
    ChevronRightIconOutline: typeof import('@heroicons/vue/outline')['ChevronRightIcon']
    ChevronUpIconOutline: typeof import('@heroicons/vue/outline')['ChevronUpIcon']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    Disclosure: typeof import('@headlessui/vue')['Disclosure']
    DisclosureButton: typeof import('@headlessui/vue')['DisclosureButton']
    DisclosurePanel: typeof import('@headlessui/vue')['DisclosurePanel']
    Form: typeof import('vee-validate')['Form']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    LockClosedIconSolid: typeof import('@heroicons/vue/solid')['LockClosedIcon']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuIconOutline: typeof import('@heroicons/vue/outline')['MenuIcon']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    MoonIconOutline: typeof import('@heroicons/vue/outline')['MoonIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SunIconOutline: typeof import('@heroicons/vue/outline')['SunIcon']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
    XIconOutline: typeof import('@heroicons/vue/outline')['XIcon']
  }
}

export {}
